openapi: 3.0.3
info:
  title: Horoscope v2 graphql
  version: 1.0.0
servers:
  - url: https://indexer-v2.dev.aurascan.io
    description: Server for testnet network. Support chains of auratestnet, serenity, euphoria, xstaxy, nois and sei
  - url: https://horoscope.aura.network
    description: Server for main network. Only support chain of xstaxy
  - url: https://indexer-v2.staging.aurascan.io
    description: Server for testnet network. Support chains of euphoria and xstaxy
tags:
  - name: cw20
paths:
  /api/v2/graphql:
    post:
      tags:
        - cw20
      summary: Query cw20 holder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cw20holder'
            examples:
              xstaxy:
                summary: Query on Xstaxy chain
                value:
                  operationName: cw20holder
                  query: 'query cw20holder($contractAddress: String = null, $limit: Int = 10) { xstaxy { cw20_holder(limit: $limit, where: {cw20_contract: {smart_contract: {address: {_eq: $contractAddress}}}}) { address amount cw20_contract_id } } }'
                  variables:
                    limit: 10
                    contractAddress: aura10kf2zul43ql7x7eqdzj9v358808pg36wa3a79h520cgakznxff8sh5mg23
              auratestnet:
                summary: Query on Aura Testnet chain
                value:
                  operationName: cw20holder
                  query: 'query cw20holder($contractAddress: String = null, $limit: Int = 10) { auratestnet { cw20_holder(limit: $limit, where: {cw20_contract: {smart_contract: {address: {_eq: $contractAddress}}}}) { address amount cw20_contract_id } } }'
                  variables:
                    limit: 10
                    contractAddress: aura10kf2zul43ql7x7eqdzj9v358808pg36wa3a79h520cgakznxff8sh5mg23
              serenity:
                summary: Query on Serenity chain
                value:
                  operationName: cw20holder
                  query: 'query cw20holder($contractAddress: String = null, $limit: Int = 10) { serenity { cw20_holder(limit: $limit, where: {cw20_contract: {smart_contract: {address: {_eq: $contractAddress}}}}) { address amount cw20_contract_id } } }'
                  variables:
                    limit: 10
                    contractAddress: aura10kf2zul43ql7x7eqdzj9v358808pg36wa3a79h520cgakznxff8sh5mg23
              euphoria:
                summary: Query on Euphoria chain
                value:
                  operationName: cw20holder
                  query: 'query cw20holder($contractAddress: String = null, $limit: Int = 10) { euphoria { cw20_holder(limit: $limit, where: {cw20_contract: {smart_contract: {address: {_eq: $contractAddress}}}}) { address amount cw20_contract_id } } }'
                  variables:
                    limit: 10
                    contractAddress: aura10kf2zul43ql7x7eqdzj9v358808pg36wa3a79h520cgakznxff8sh5mg23
              nois:
                summary: Query on Nois chain
                value:
                  operationName: cw20holder
                  query: 'query cw20holder($contractAddress: String = null, $limit: Int = 10) { nois { cw20_holder(limit: $limit, where: {cw20_contract: {smart_contract: {address: {_eq: $contractAddress}}}}) { address amount cw20_contract_id } } }'
                  variables:
                    limit: 10
                    contractAddress: aura10kf2zul43ql7x7eqdzj9v358808pg36wa3a79h520cgakznxff8sh5mg23
              sei:
                summary: Query on Sei chain
                value:
                  operationName: cw20holder
                  query: 'query cw20holder($contractAddress: String = null, $limit: Int = 10) { sei { cw20_holder(limit: $limit, where: {cw20_contract: {smart_contract: {address: {_eq: $contractAddress}}}}) { address amount cw20_contract_id } } }'
                  variables:
                    limit: 10
                    contractAddress: aura10kf2zul43ql7x7eqdzj9v358808pg36wa3a79h520cgakznxff8sh5mg23
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    cw20holder:
      type: object
      properties:
        operationName:
          type: string
          example: cw20holder
          description: query name
        query:
          type: string
          example: 'query cw20holder($contractAddress: String = null, $limit: Int = 10) { euphoria { cw20_holder(limit: $limit, where: {cw20_contract: {smart_contract: {address: {_eq: $contractAddress}}}}) { address amount cw20_contract_id } } }'
          description: Graphql query
        variables:
          type: object
          description: Variable in query
          example:
            limit: 10
            contractAddress: aura10kf2zul43ql7x7eqdzj9v358808pg36wa3a79h520cgakznxff8sh5mg23
