openapi: 3.0.3
info:
  title: Horoscope v2 graphql
  version: 1.0.0
servers:
  - url: https://indexer-v2.dev.aurascan.io
    description: Server for testnet network. Support chains of auratestnet, serenity, euphoria, xstaxy, nois and sei
  - url: https://horoscope.aura.network
    description: Server for main network. Only support chain of xstaxy
  - url: https://indexer-v2.staging.aurascan.io
    description: Server for testnet network. Support chains of euphoria and xstaxy
tags:
  - name: proposal
paths:
  /api/v2/graphql:
    post:
      tags:
        - proposal
      summary: Query proposal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/proposal'
            examples:
              xstaxy:
                summary: Query on Xstaxy chain
                value:
                  operationName: queryProposal
                  query: "query queryProposal($limit: Int = 10, $offset: Int = 0, $order: order_by = desc, $proposalId: Int = null, $type: String = null) { xstaxy { proposal(limit: $limit, offset: $offset, where: {proposal_id: {_eq: $proposalId}, type: {_eq: $type}}, order_by: {proposal_id: $order}) { content deposit_end_time description initial_deposit proposal_id proposer_address count_vote proposer { description operator_address account_address } status submit_time tally title total_deposit turnout type updated_at voting_end_time voting_start_time } proposal_aggregate(where: {proposal_id: {_eq: $proposalId}, type: {_eq: $type}}) { aggregate { count } } } }"
                  variables:
                    order: desc
                    limit: 4
              auratestnet:
                summary: Query on Aura Testnet chain
                value:
                  operationName: queryProposal
                  query: "query queryProposal($limit: Int = 10, $offset: Int = 0, $order: order_by = desc, $proposalId: Int = null, $type: String = null) { auratestnet { proposal(limit: $limit, offset: $offset, where: {proposal_id: {_eq: $proposalId}, type: {_eq: $type}}, order_by: {proposal_id: $order}) { content deposit_end_time description initial_deposit proposal_id proposer_address count_vote proposer { description operator_address account_address } status submit_time tally title total_deposit turnout type updated_at voting_end_time voting_start_time } proposal_aggregate(where: {proposal_id: {_eq: $proposalId}, type: {_eq: $type}}) { aggregate { count } } } }"
                  variables:
                    order: desc
                    limit: 4
              serenity:
                summary: Query on Serenity chain
                value:
                  operationName: queryProposal
                  query: "query queryProposal($limit: Int = 10, $offset: Int = 0, $order: order_by = desc, $proposalId: Int = null, $type: String = null) { serenity { proposal(limit: $limit, offset: $offset, where: {proposal_id: {_eq: $proposalId}, type: {_eq: $type}}, order_by: {proposal_id: $order}) { content deposit_end_time description initial_deposit proposal_id proposer_address count_vote proposer { description operator_address account_address } status submit_time tally title total_deposit turnout type updated_at voting_end_time voting_start_time } proposal_aggregate(where: {proposal_id: {_eq: $proposalId}, type: {_eq: $type}}) { aggregate { count } } } }"
                  variables:
                    order: desc
                    limit: 4
              euphoria:
                summary: Query on Euphoria chain
                value:
                  operationName: queryProposal
                  query: "query queryProposal($limit: Int = 10, $offset: Int = 0, $order: order_by = desc, $proposalId: Int = null, $type: String = null) { euphoria { proposal(limit: $limit, offset: $offset, where: {proposal_id: {_eq: $proposalId}, type: {_eq: $type}}, order_by: {proposal_id: $order}) { content deposit_end_time description initial_deposit proposal_id proposer_address count_vote proposer { description operator_address account_address } status submit_time tally title total_deposit turnout type updated_at voting_end_time voting_start_time } proposal_aggregate(where: {proposal_id: {_eq: $proposalId}, type: {_eq: $type}}) { aggregate { count } } } }"
                  variables:
                    order: desc
                    limit: 4
              nois:
                summary: Query on Nois chain
                value:
                  operationName: queryProposal
                  query: "query queryProposal($limit: Int = 10, $offset: Int = 0, $order: order_by = desc, $proposalId: Int = null, $type: String = null) { nois { proposal(limit: $limit, offset: $offset, where: {proposal_id: {_eq: $proposalId}, type: {_eq: $type}}, order_by: {proposal_id: $order}) { content deposit_end_time description initial_deposit proposal_id proposer_address count_vote proposer { description operator_address account_address } status submit_time tally title total_deposit turnout type updated_at voting_end_time voting_start_time } proposal_aggregate(where: {proposal_id: {_eq: $proposalId}, type: {_eq: $type}}) { aggregate { count } } } }"
                  variables:
                    order: desc
                    limit: 4
              sei:
                summary: Query on Sei chain
                value:
                  operationName: queryProposal
                  query: "query queryProposal($limit: Int = 10, $offset: Int = 0, $order: order_by = desc, $proposalId: Int = null, $type: String = null) { sei { proposal(limit: $limit, offset: $offset, where: {proposal_id: {_eq: $proposalId}, type: {_eq: $type}}, order_by: {proposal_id: $order}) { content deposit_end_time description initial_deposit proposal_id proposer_address count_vote proposer { description operator_address account_address } status submit_time tally title total_deposit turnout type updated_at voting_end_time voting_start_time } proposal_aggregate(where: {proposal_id: {_eq: $proposalId}, type: {_eq: $type}}) { aggregate { count } } } }"
                  variables:
                    order: desc
                    limit: 4
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    proposal:
      type: object
      properties:
        operationName:
          type: string
          example: queryProposal
          description: query name
        query:
          type: string
          example: "query queryProposal($limit: Int = 10, $offset: Int = 0, $order: order_by = desc, $proposalId: Int = null, $type: String = null) { serenity { proposal(limit: $limit, offset: $offset, where: {proposal_id: {_eq: $proposalId}, type: {_eq: $type}}, order_by: {proposal_id: $order}) { content deposit_end_time description initial_deposit proposal_id proposer_address count_vote proposer { description operator_address account_address } status submit_time tally title total_deposit turnout type updated_at voting_end_time voting_start_time } proposal_aggregate(where: {proposal_id: {_eq: $proposalId}, type: {_eq: $type}}) { aggregate { count } } } }"
          description: Graphql query
        variables:
          type: object
          description: Variable in query
          example:
            order: desc
            limit: 4
            
          
            
