/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-nocheck

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  overview: [
    'overview/index',
    // {
    //     type: 'html',
    //     value: '<hr/>'
    // },
    {
      type: 'html',
      value: '<b>Overview</b>',
      className: 'sidebar_category'
    },
    { type: 'autogenerated', dirName: 'overview/about' },
    {
      type: 'html',
      value: '<hr/>'
    },
    {
      type: 'html',
      value: '<b>Getting started</b>',
      className: 'sidebar_category'
    },
    { type: 'autogenerated', dirName: 'overview/start' },
    {
      type: 'html',
      value: '<hr/>'
    },
    {
      type: 'html',
      value: '<b>Concepts</b>',
      className: 'sidebar_category'
    },
    { type: 'autogenerated', dirName: 'overview/protocol' },
    {
      type: 'html',
      value: '<hr/>'
    },
    {
      type: 'html',
      value: '<b>FAQs</b>',
      className: 'sidebar_category'
    },
    { type: 'autogenerated', dirName: 'overview/faq' }
  ],
  developer: [
    { type: 'autogenerated', dirName: 'developer' }
  ],
  validator: [
    { type: 'autogenerated', dirName: 'validator' }
  ],
  pyxissafe: [
    'product/pyxis-safe/index',
    {
      type: 'category',
      label: '<b>Getting Started</b>',
	  collapsible: true,
      collapsed: false,
      items: [
        {
		type: 'autogenerated',
		dirName: 'product/pyxis-safe/getting-started'
		}
      ]
    },
	{
      type: 'category',
      label: '<b>Making transactions</b>',
	  collapsible: true,
      collapsed: false,
      items: [
        {
		type: 'autogenerated',
		dirName: 'product/pyxis-safe/making-transaction'
		}
      ]
    },
	{
      type: 'category',
      label: '<b>Going Further</b>',
	  collapsible: true,
      collapsed: true,
      items: [
        {
		type: 'autogenerated',
		dirName: 'product/pyxis-safe/going-further'
		}
      ]
    },
	{
      type: 'category',
      label: '<b>Extras</b>',
	  collapsible: true,
      collapsed: true,
      items: [
        {
		type: 'autogenerated',
		dirName: 'product/pyxis-safe/extras'
		}
      ]
    },   
  ],
  aurascan: [
    'product/aurascan/index',
    {
      type: 'html',
      value: '<hr/>'
    },
    {
      type: 'html',
      value: '<b>Getting Started</b>',
      className: 'sidebar_category'
    },
    {
      type: 'autogenerated',
      dirName: 'product/aurascan/getting-started'
    },
    {
      type: 'html',
      value: '<hr/>'
    },
    {
      type: 'html',
      value: '<b>Advanced Topics</b>',
      className: 'sidebar_category'
    },
    {
      type: 'autogenerated',
      dirName: 'product/aurascan/advanced-topics'
    }
  ],
  horoscope: [
    'product/horoscope/index',
    {
      type: 'html',
      value: '<hr/>'
    },
    {
      type: 'html',
      value: 'Architecture',
      className: 'sidebar_category'
    },
    {
      type: 'autogenerated',
      dirName: 'product/horoscope/architecture'
    },
    {
      type: 'html',
      value: '<hr/>'
    },
    {
      type: 'category',
      label: 'API',
      collapsible: false,
      items: require('./docs/horoscope/sidebar'),
    },
  ],
  integrate: [
    {
      type: 'html',
      value: '<b>Exchange integration</b>',
      className: 'sidebar_category'
    },
    { type: 'autogenerated', dirName: 'integrate/exchange' },
    {
      type: 'html',
      value: '<hr/>'
    },
    {
      type: 'html',
      value: '<b>Wallet integration</b>',
      className: 'sidebar_category'
    },
    { type: 'autogenerated', dirName: 'integrate/wallet' },
  ],
};

module.exports = sidebars;
