/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  overview: [{ type: 'autogenerated', dirName: 'overview' }],
  developer: [
    { type: 'autogenerated', dirName: 'developer' },
    {
      type: "category",
      label: "🔌 Horoscope Indexer",
      link: {
        type: "generated-index",
        title: "Horoscope API",
      },
      items: require("./docs/horoscope/sidebar"),
    },
  ],
  validator: [{ type: 'autogenerated', dirName: 'validator' }],
  pyxissafe: [
  "product/pyxis-safe/index",
	{
      "type": "html",
      "value": "<hr/>"
    },
	{
      "type": "html",
	  "value": "<b>▶️ Getting Started</b>",
	  "className": 'sidebar_category'
    },
	{ 
		type: 'autogenerated', 
		dirName: 'product/pyxis-safe/getting-started' 
	},
	{
      "type": "html",
      "value": "<hr/>"
    },
	{
      "type": "html",
	  "value": "<b>⏩ Going Further</b>",
	  "className": 'sidebar_category'
    },
	{ 
		type: 'autogenerated', 
		dirName: 'product/pyxis-safe/going-further' 
	}
	],
  aurascan: [
  "product/aurascan/index",
	{
      "type": "html",
      "value": "<hr/>"
    },
	{
      "type": "html",
	  "value": "<b>▶️ Getting Started</b>",
	  "className": 'sidebar_category'
    },
	{ 
		type: 'autogenerated', 
		dirName: 'product/aurascan/getting-started' 
	},
	{
      "type": "html",
      "value": "<hr/>"
    },
	{
      "type": "html",
	  "value": "<b>⏩ Advanced Topics</b>",
	  "className": 'sidebar_category'
    },
	{ 
		type: 'autogenerated', 
		dirName: 'product/aurascan/advanced-topics' 
	}
	
	],
  exchange: [{ type: 'autogenerated', dirName: 'exchange' }],

  
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
